baseURL = "https://app.javyhuerta.com/"
languageCode = "es-mx"
title = "Caja de Herramientas"
theme = "slate"

publishDir = "docs"

[ params ]
Favicon = "favicon.ico"
OpenLinksInNewWindow = true

[[ params.nav ]]
name = "shopping"
tag = "shopping"
icon = "shopping-basket"


[[ params.nav ]]
name = "Banco de imagenes"
tag = "img"
icon = "file-image-o"

[[ params.nav ]]
name = "Fuentes"
tag = "font"
icon = "font"

[[ params.nav ]]
name = "Misceláneos"
tag = "otros"
icon = "random"

[[ params.nav ]]
name = "Herramientas de programacion"
tag = "programaciontools"
icon = "code"

[[ params.nav ]]
name = "Banco de videos"
tag = "banvideo"
icon = "file-video-o"

[[ params.nav ]]
name = "Inversiones"
tag = "inversiones"
icon = "money"

[[ params.nav ]]
name = "Hosting y/o Dominio"
tag = "internet"
icon = "server"

[[ params.nav ]]
name = "Email Marketing"
tag = "email"
icon = "envelope-open-o"

[[ params.nav ]]
name = "Cursos"
tag = "cursos"
icon = "play-circle"